apiVersion: v1
kind: ReplicationController
metadata:
  name: logindetails-rc
spec:
  replicas: 3
  selector:
    app: logindetails
  template:
    metadata:
      name: logindetails
      labels:
        app: logindetails
    spec:
      containers:
        - name: logindetails-container
          image: maha4iac/myonlinebooking:2
          ports:
            - containerPort: 8080
