apiVersion: v1
kind: Service
metadata:
  name: logindetails-svc
  labels:
     app: logindetails
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 80001
    protocol: TCP
  selector:
    app: logindetails
